### ISSUE TITLE
Assorted faces I've created

### ISSUE THREAD

**Issue by justarandomgeek** [leighmcculloch/looks.wtf#1]
I spent far too long some years ago making faces, here's some of the highlights if you want to include any of them:

Pulling a rabbit from a hat (I used to post these in-sequence on Omegle, if done quickly it sort of animates)
\_▄\_
\\ •̮•

(\\_/)
¯▀¯

(\\_/)
(^̮ ̮^)
¯▀¯

(\\_/)
(^̮ ̮^)
£ £ ) 

Nyancat
≋̯̫⌧̯̫(ˆ•̮ ̮•ˆ)
≋≋≋≋≋̯̫⌧̯̫(ˆ•̮ ̮•ˆ) 

A group of double-smile faces (probably too simple to be worth listing all of, but they're here, so why not)
^̮ ̮^
ᴖ̮ ̮ᴖ
•̮ ̮•

And last but not least, a pair of tiny faces:
.̯. .̮.

Edit: oops, seems I have to escape some of these on github!

**Comment by leighmcculloch** [comment]
Thanks! Adding them now.

**Comment by leighmcculloch** [comment]
Included in ^ and deployed.
