### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by jbcpollak** [leighmcculloch/looks.wtf#4]
Would be yuge!

**Comment by leighmcculloch** [comment]
@jbcpollak: I'm open to supporting that. What sort of functions would you be interested in?

**Comment by jbcpollak** [comment]
I'm thinking of something like:

```
/look lenny -> ͡° ͜ʖ ͡°
/look doubtful -> ಠಿ_ಠ
/look sweet -> (☞ﾟヮﾟ)☞
```

Something like that. Similar to the way the /giphy command works

**Comment by leighmcculloch** [comment]
@jbcpollak: Give it a whirl. Hit the Add to Slack button that is at the bottom of the [looks.wtf](https://looks.wtf) pages to add the `/look` command to your Slack. Then you can type `/look happy`. 😄

**Comment by jbcpollak** [comment]
Works great! It would be nice to be able to have explicit access to all the faces specifically, but this is pretty awesome, thanks!

```
/look awe
looks.wtf BOT [11:27 AM] 
ʘ‿ʘ
```

**Comment by leighmcculloch** [comment]
@jbcpollak: Can you elaborate on how the explicit access would work?

**Comment by jbcpollak** [comment]
I'm not 100% sure - but I figured each one would have a text code associated with it. Lets say I wanted this one:

`ó‿ó`

on the website, it doesn't have a name, but lets say its called `happy_brows`, you could do:

`/look happy_brows`

and get that back. I guess there would be 100's of codes, but you could learn your favorites and even ask `/look help awe` maybe to get all the codes in the `awe` category.

Something like that at least. :)
