### ISSUE TITLE
can you add this to your list

### ISSUE THREAD

**Issue by vasanthaganeshk** [leighmcculloch/looks.wtf#7]
(*˘︶˘*).｡.:*♡﻿

**Comment by leighmcculloch** [comment]
💯

**Comment by leighmcculloch** [comment]
If your up for opening a PR you just need to add the new look to the following yml files like so:

https://github.com/leighmcculloch/looks.wtf/blob/5145be7/slackcommandlook/looks.yml#L950-L952

https://github.com/leighmcculloch/looks.wtf/blob/5145be7/website/data/looks.yml#L950-L952

**Comment by vasanthaganeshk** [comment]
checkout #8
