### ISSUE TITLE
Multi–line looks

### ISSUE THREAD

**Issue by LeBaux** [leighmcculloch/looks.wtf#9]
Maybe in separate category? Would be neato. •ᴥ•
https://gist.github.com/cheeaun/3720871
(also low key checking if you are watching the repo)

**Comment by leighmcculloch** [comment]
This is a cool idea. I wonder how they can be presented in a compact space? I'm thinking display one line at a time in succession, like a gif, but when copying then the browser PRs the entire thing into the clipboard.

**Comment by LeBaux** [comment]
Oh hi! Thanks for making unbloated ascii–meme directory–thing! I don’t know how many cool multi–line looks are there. I know about 2, 3? Personally, I would worry about space when the time comes. If ever.

> when copying then the browser PRs the entire thing into the clipboard.
Sounds good to me.

**Comment by leighmcculloch** [comment]
Multi-line looks are supported. For example:
<img width="158" alt="Screenshot 2023-07-18 at 9 01 33 AM" src="https://github.com/leighmcculloch/looks.wtf/assets/351529/9e13a1c4-015a-4e7e-8b6f-57cc62e228de">
